name: Generate Snake

on:
  schedule:
    - cron: "0 10 * * *"   # chạy ~17:00 VN mỗi ngày
  workflow_dispatch:       # cho phép chạy tay từ tab Actions

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ngovanhuyhoang
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif?color_snake=purple

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p dist
          git add dist/*
          git commit -m "chore: update snake" || echo "no changes"
          git push
